### ISSUE TITLE
video_preprocess.py

### ISSUE THREAD

**Issue by Stanly-19** [thuiar/MIntRec#11]
您好，我最近在尝试使用您的video_preprocess对我的视频进行处理，但是遇到了几个问题，首先是TalkNet，请问这是要自行寻找的吗
![image](https://github.com/thuiar/MIntRec/assets/73524246/543983e4-8dba-47f8-9bfd-14ff993ff784)
第二个问题是我想知道video_preprocess的输入内容是什么，是视频吗？我已经将视频放在下述的文件夹了，但是依旧没有效果
![image](https://github.com/thuiar/MIntRec/assets/73524246/60ae9711-5ca5-460e-8ecc-d5ec7964ee88)

**Comment by HanleiZhang** [comment]
您好，我们已经开源抽取视频关键帧相关的代码在目录[TalkNet_ASD](https://github.com/thuiar/MIntRec/tree/main/TalkNet_ASD)
