### ISSUE TITLE
Code issues

### ISSUE THREAD

**Issue by ShilinSun** [thuiar/MIntRec#15]
Hello, I have followed the deployment in the readme file, but the results from the run are train_loss = nan, best_eval_score = 0.0114, eval_score = 0.0114. What could be the reason for this?

**Comment by ShilinSun** [comment]
Sorry, I was having problems with some of my packages, the above issues have been resolved.

**Comment by saransh03sharma** [comment]
Could you point out what was the issue? I am facing the same thing right now.

**Comment by ShilinSun** [comment]
I recreated the environment's repository as described in the readme file and downloaded the relevant packages, and the issue was resolved.
