### ISSUE TITLE
audio_feats load 报错

### ISSUE THREAD

**Issue by xuejianhuang** [thuiar/MIntRec#4]
大佬您好！   我在运行您的代码时audio_pre.py中的这行audio_feats = pickle.load(f)代码报错，提示ValueError: could not convert string to float，您知道什么原因吗？

**Comment by xuejianhuang** [comment]
我换成Google云盘的audio_feats.pkl就没问题了，应该是百度云盘上的audio_feats.pkl这文件有问题

**Comment by mrFocusXin** [comment]
@xuejianhuang  感谢你的关注，我们已经更新了百度云网盘上有问题的文件。
