### ISSUE TITLE
The video_preprocess.py

### ISSUE THREAD

**Issue by SWXxing** [thuiar/MIntRec#7]
Is args.TalkNet_speaker_path an empty folder? args.TalkNet_speaker_path="MIA/datasets/speaker_annotation/Talknet"
![image](https://user-images.githubusercontent.com/129766795/229539372-87806706-20dd-427d-a4e6-7ed4b08aaa2d.png)

**Comment by katerynaCh** [comment]
I have the same question, similarly what is supposed to be 'best_persons.npy' and 'pyframes'?

**Comment by HanleiZhang** [comment]
We have released the full codes of the automatic speaker annotation process in the [TalkNet_ASD](https://github.com/thuiar/MIntRec/tree/main/TalkNet_ASD) directory, enjoy it!
